### ISSUE TITLE
node-opcua events values are empty (Prosys simulator)

### ISSUE THREAD

**Issue by aklauss** [BiancoRoyal/node-red-contrib-iiot-opcua#207]
Hello.
I am trying to get OPCUA events from  Prosys simulator using one the availables examples and I am getting an empty value's array  as the response.

Information:
node.js: 16.17.0
node-red version: 3.0.2
node-red-contrib-iiot-opcua: 4.0.11
node-opcua: 2.64.1

Response:
{"payload":{"addressSpaceItems":[{"name":"","nodeId":"ns=0;i=2253","datatypeName":""}],"nodetype":"listen","injectType":"event","value":[]},"topic":"","_msgid":"82c94e0e08609d8c"}

Thanks
Antonio Klauss

**Comment by JoelKrec** [comment]
Hello Antonio,
We could reproduce your error but sadly we weren't able to extract the core problem for now. When we create the monitored item we rely on an "item_added" event. There, we receive no data and a bad status code by node-opcua with the following error message: "Expected data is unavailable for the requested time range due to an 
  un-mounted volume, an off-line archive or tape, or similar reason for temporary unavailability. "
Maybe it is a problem of node-opcua but sadly we don't have enough time to go to the bottom of this before the next minor release. 

We will keep it in mind, though and update you, if we find out more!

With some financial support we could maybe rearrange our priorities and focus on this problem, if you are willing to help and this is really important to you.

**Comment by caccia86** [comment]
Hi, I encountered the same problem too, any suggests?
I can't retrieve data from events generated by OPC UA EUROMAP77 model...

[flows.json](https://github.com/BiancoRoyal/node-red-contrib-iiot-opcua/files/13116753/flows.json)

![image](https://github.com/BiancoRoyal/node-red-contrib-iiot-opcua/assets/148060442/300644b8-5152-4a73-887b-59f01612b9a7)

![image](https://github.com/BiancoRoyal/node-red-contrib-iiot-opcua/assets/148060442/c71d24c9-2ec8-4c35-ab86-150fbaef7151)

![image](https://github.com/BiancoRoyal/node-red-contrib-iiot-opcua/assets/148060442/2a0030f5-e8dc-47e5-be66-ef1ab049a8e4)

Thanks in advance for whatever support

**Comment by JoelKrec** [comment]
Hello @caccia86

As you can see, we already tried to solve this problem and could not find an easy solution. Because of how old this package is and time reasons, we also decided to halt development of this package and create an up-to-date OPC UA package which is not open source at the moment. There are plans to make an open source version of it but that is not for me to decide. 

If you are using this package commercially and want the new premium package, contact us directly and ask for PLUS for Node-RED OPC UA Package.

If you do not want this, there is still the other open source package node-red-contrib-opcua. Maybe it works better than this package.

You could also develop a solution yourself with a fork and a pull request as this package is open source. Help developing is much appreciated.
