### ISSUE TITLE
"Error: Session Not Valid On Write"

### ISSUE THREAD

**Issue by JoaoMCPereira** [BiancoRoyal/node-red-contrib-iiot-opcua#25]
I'm new to node-red and to OPC-UA. After installing node-red and this module I run a few examples and always got the same error message saying "Error: Session Not Valid On Write" 
I also copy the examples 'write.json', 'read.json' and 'server-demo.json' but same error message is showing up.
What I'm missing? I need to install something else besides 'node-red-node-data-generator'?

Thanks for the help

**Comment by w4tsn** [comment]
My Issue #26 might be related since it throws the error `Error: Session Not Valid On Read`. As of my understanding the Connector-Node could not connect to the OPC-UA server, so the read/write nodes can't access the server endpoint.

What I had to do in order to get the examples to work was:

1. enable anonymous access in the server node
2. allow non-existing endpoint in the connector-node `LOCAL SERVER`

**Comment by biancode** [comment]
<img width="608" alt="grafik" src="https://user-images.githubusercontent.com/4369867/37240453-de0aa1da-244b-11e8-88ff-0749a8fed073.png">

or set/check the endpoint uri is correct

**Comment by biancode** [comment]
do not inject read, listen or write before server is ready - use the start delay with some seconds
