### ISSUE TITLE
npm WARN deprecated vm2@3.9.19

### ISSUE THREAD

**Issue by hadi-saeidi** [BiancoRoyal/node-red-contrib-iiot-opcua#252]
### Describe the requested feature

npm WARN deprecated vm2@3.9.19: The library contains critical security issues and should not be used for production! The maintenance of the project has been discontinued. Consider migrating your code to **isolated-vm**

### Motivation

Solve Security Problem

**Comment by JoelKrec** [comment]
Hello @hadi-saeidi 

We halted development of this package because of time and financial reasons. If you want this fixed anyway, please contact us directly via email or consider becoming a customer for the new premium package which we created to solve many issues and usage of modern dependencies.

We hope that a community will pick this package up and continue development but in our experience not many people will seriously develop for this package. So we decided to wait for december and then make this package deprecated if nobody started working on this. Either way, we do not recommend using this package, nor trying to work on it, as it is quite old and it would need breaking changes for many dependencies to be updated. Also, with time many small problems became visible which are so deeply woven into the project that most of them are unfixable. This was the reason we decided to start all over again with a fresh, new and modern package.
